### ISSUE TITLE
Issues compiling and running

### ISSUE THREAD

**Issue by puterboy** [TheBiggerGuy/photooxide#272]
Running "cargo run -- photo_mount" triggers the below build error presumably due to a lack of fuse.pc
I have never used rust before and just installed 'rustc' on my Ubuntu 18.04 system.

```
error: failed to run custom build command for `fuse v0.3.1`

Caused by:
  process didn't exit successfully: `/home/myuser/src/photooxide/target/debug/build/fuse-902574c25a007ba1/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\" \"fuse >= 2.6.0\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'fuse' found\nPackage fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'fuse' found\n" } }', /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/build.rs:10:76
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

- Any idea on how to fix this error?

- Also, I noted that running 'cargo run -- photo_mount' adds about 0.5G each to ~/.cargo and to  ~/src/photooxide. So, What if anything can be deleted after the build is completed?

**Comment by puterboy** [comment]
I solved the first question as it seems I needed to install 'libfuse-dev'.
But now I am getting a new build error: 

```
error: couldn't read src/../client_secret.json: No such file or directory (os error 2)
  --> src/main.rs:49:29
   |
49 | const CLIENT_SECRET: &str = include_str!("../client_secret.json");
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `photooxide`
```

Also, still curious about the second question in terms of what I can delete...

**Comment by puterboy** [comment]
OK - seems like I need to manually create ../photooxide/client_secret.json to get it to build...

**Comment by puterboy** [comment]
I can now get it to build and I successfully figured out how to generate my own GCP project with my own unique:
- client_id
- client_secret
- project_id
that I then paste into client_secret.json

However, when I run: 'cargo run -- ../photo_mount',
I get the following error:
```
   Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/photooxide ../photo_mount`
[2022-02-06T18:58:09Z INFO  photooxide] Logging init
[2022-02-06T18:58:09Z INFO  photooxide] starting FUSE mount at "../photo_mount" with ["-o", "ro", "-o", "fsname=photooxide"]
[2022-02-06T18:58:14Z WARN  photooxide::background_update] Start background albums refresh
[2022-02-06T18:58:15Z DEBUG photooxide::photolib] Success: listing albums
[2022-02-06T18:58:16Z DEBUG photooxide::photolib] Success: listing albums
[2022-02-06T18:58:16Z DEBUG photooxide::photolib] Success: listing albums
thread 'pool_thread_0' panicked at 'called `Option::unwrap()` on a `None` value', src/photolib/mod.rs:134:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any ideas about what is causing this to fail?

Note the backtrace follows:

```
thread 'pool_thread_0' panicked at 'called `Option::unwrap()` on a `None` value', src/photolib/mod.rs:134:47
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/core/src/option.rs:386:21
   4: <photooxide::photolib::HttpRemotePhotoLib<C,A> as photooxide::photolib::RemotePhotoLibMetaData>::albums
             at ./src/photolib/mod.rs:134:34
   5: <photooxide::background_update::BackgroundAlbumUpdate<C,A> as photooxide::background_update::BackgroundUpdate>::update
             at ./src/background_update.rs:56:22
   6: photooxide::main::{{closure}}
             at ./src/main.rs:121:91
   7: scheduled_executor::executor::ThreadPoolExecutor::schedule_fixed_rate::{{closure}}::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/scheduled-executor-0.4.0/src/executor.rs:256:21
   8: futures::future::lazy::Lazy<F,R>::get
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/lazy.rs:64:59
   9: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/lazy.rs:82:9
  10: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/catch_unwind.rs:49:9
  11: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/catch_unwind.rs:32:46
  12: std::panicking::try::do_call
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:379:40
  13: __rust_try
  14: std::panicking::try
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:343:19
  15: std::panic::catch_unwind
             at /build/rustc-fdjxBl/rustc-1.53.0+dfsg1+llvm/library/std/src/panic.rs:431:14
  16: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/catch_unwind.rs:32:29
  17: <futures_cpupool::MySender<F,core::result::Result<<F as futures::future::Future>::Item,<F as futures::future::Future>::Error>> as futures::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs:325:25
  18: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/mod.rs:113:13
  19: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:329:45
  20: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:399:27
  21: futures::task_impl::std::set
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:83:13
  22: futures::task_impl::Spawn<T>::enter
             at /home/muser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:399:9
  23: futures::task_impl::Spawn<T>::poll_fn_notify
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:291:9
  24: futures::task_impl::Spawn<T>::poll_future_notify
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:329:9
  25: futures::task_impl::std::Run::run
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:425:23
  26: futures_cpupool::Inner::work
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs:257:36
  27: futures_cpupool::Builder::create::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs:427:42
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by a0s** [comment]
stopped in the same place, need help of @TheBiggerGuy
